name: code-coverage

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/release.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BEBIT_MACHINE_GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle
      - name: test
        run: ./gradlew test
        env:
          GITHUB_ACTOR: bebit-machine
          GITHUB_TOKEN: ${{ secrets.BEBIT_MACHINE_GITHUB_TOKEN }}
      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          jacoco-csv-file: processor/build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: true
          generate-summary: true
      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'
      - name: Commit and push the coverage-summary (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit coverage-summary'
          add: '*.json'
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: processor/build/reports/jacoco/
