name: code-coverage

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/release.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BEBIT_MACHINE_GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle
      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: true
      - uses: actions/checkout@v2
        with:
          ref: code-coverage
      - name: Setup github account
        run: |
          git config --local user.email "putri3039@gmail.com"
          git config --local user.name "rizky-meiliasari-bebit"
      - name: Commit files
        run: |
          git add .github/badges
          git commit -m "Update latest code-coverage" -a
          git pull origin patch-2
          git push origin patch-2:coverage-badge -f
